swagger: '2.0'
info:
  version: '1.0'
  description: My Retail API
  title: My Retail API
host: localhost:9091
basePath: /my_retail
tags:
  - name: details-controller
    description: Details Aggregator Controller
  - name: prices-controller
    description: Prices Core Controller
paths:
  '/details/v1/products/{product_id}':
    get:
      tags:
        - details-controller
      summary: Get details by ProductId
      operationId: getDetailsByProductIdUsingGET
      produces:
        - application/json
      parameters:
        - name: "key"
          in: "query"
          description: Valid api key.
          required: true
          type: "string"
        - name: "authorization"
          in: "header"
          description: Valid authorization bearer token.
          required: true
          type: "string"
        - name: product_id
          in: path
          description: product id
          required: true
          type: integer
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DetailsResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error
  '/prices/v1/products/{product_id}':
    post:
      tags:
        - prices-controller
      summary: Create Prices for ProductId
      operationId: createPricesForProductIdUsingPOST
      produces:
        - application/json
      parameters:
        - name: "key"
          in: "query"
          description: Valid api key.
          required: true
          type: "string"
        - name: "authorization"
          in: "header"
          description: Valid authorization bearer token.
          required: true
          type: "string"
        - name: product_id
          in: path
          description: product id
          required: true
          type: integer
        - name: body
          in: body
          description: price to update
          required: true
          schema:
            $ref: '#/definitions/AllPrices'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PricesDocument'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error
    get:
      tags:
        - prices-controller
      summary: Get prices by ProductId
      operationId: getPricesByProductIdUsingGET
      produces:
        - application/json
      parameters:
        - name: "key"
          in: "query"
          description: Valid api key.
          required: true
          type: "string"
        - name: "authorization"
          in: "header"
          description: Valid authorization bearer token.
          required: true
          type: "string"
        - name: product_id
          in: path
          description: product id
          required: true
          type: integer
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PricesDocument'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error
  '/prices/v1/products/{product_id}/price_types/{price_type}':
    put:
      tags:
        - prices-controller
      summary: Update product price for a price type by ProductId
      operationId: updatePricesForProductIdPUT
      produces:
        - application/json
      parameters:
        - name: "x-api-key"
          in: "header"
          description: Valid api key.
          required: true
          type: "string"
        - name: "authorization"
          in: "header"
          description: Valid authorization bearer token.
          required: true
          type: "string"
        - name: product_id
          in: path
          description: product_id
          required: true
          type: integer
          format: int64
        - name: price_type
          in: path
          description: price_type
          required: true
          type: string
        - name: body
          in: body
          description: price to update
          required: true
          schema:
            $ref: "#/definitions/Price"
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PricesDocument'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error
      deprecated: false
definitions:
  DetailsResponse:
    type: object
    required:
      - product_id
      - name
      - current_price
    properties:
      product_id:
        type: integer
        example: 7438248
      name:
        type: string
        example: Acme Glue
      current_price:
        $ref: '#/definitions/Price'
    title: Details Response
  AllPrices:
    type: object
    properties:
      current_price:
        $ref: '#/definitions/Price'
      initial_price:
        $ref: '#/definitions/Price'
      regular_price:
        $ref: '#/definitions/Price'
    title: AllPrices
  Price:
    type: object
    required:
      - currency_code
      - value
    properties:
      currency_code:
        type: string
        example: USD
      value:
        type: number
        format: double
        example: 13.99
    title: Price
  PricesDocument:
    type: object
    required:
      - prices
      - product_id
    properties:
      prices:
        $ref: '#/definitions/AllPrices'
      product_id:
        type: integer
        format: int64
    title: PricesDocument
    