version: "3.7"
services:
  mongo:
    image: mongo:latest
    tmpfs: /data/db
    ports:
      - "27081:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: prices
